export const CHAT_NEW_MESSAGE_SUCCESS = 'CHAT_NEW_MESSAGE_SUCCESS';
export const CHAT_NEW_MESSAGE_REQUEST = 'CHAT_NEW_MESSAGE_REQUEST';
export const CHAT_NEW_MESSAGE_FAILURE = 'CHAT_NEW_MESSAGE_FAILURE';
export const CHAT_MESSAGES_FAILURE = 'CHAT_MESSAGES_FAILURE';
export const CHAT_MESSAGES_SUCCESS = 'CHAT_MESSAGES_SUCCESS';
export const CHAT_MESSAGES_REQUEST = 'CHAT_MESSAGES_REQUEST';
