export const FETCH_CHAT_REQUEST = 'FETCH_CHAT_REQUEST';
export const FETCH_CHAT_SUCCESS = 'FETCH_CHAT_SUCCESS';
export const FETCH_CHAT_FAILURE = 'FETCH_CHAT_FAILURE';
export const CHAT_CLEAR_UNREAD = 'CHAT_CLEAR_UNREAD';
export const CHAT_INCREMENT_UNREAD = 'CHAT_INCREMENT_UNREAD';
export const NEW_CHAT_SUCCESS = 'NEW_CHAT_SUCCESS';