export const FETCH_CHAT_REQUEST = 'FETCH_CHAT_REQUEST';
export const FETCH_CHAT_SUCCESS = 'FETCH_CHAT_SUCCESS';
export const FETCH_CHAT_FAILURE = 'FETCH_CHAT_FAILURE';
export const NEW_CHAT_SUCCESS = 'NEW_CHAT_SUCCESS';
export const CHAT_NEW_MESSAGE = 'CHAT_NEW_MESSAGE';
export const CHAT_HISTORY_SUCCESS = 'CHAT_HISTORY_SUCCESS';
